/**
 * Licensed to Jasig under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Jasig licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a
 * copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.29 at 01:07:29 PM CDT 
//


package org.jasig.schedassist.messaging;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jasig.schedassist.messages package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jasig.schedassist.messages
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RelationshipList }
     * 
     */
    public RelationshipList createRelationshipList() {
        return new RelationshipList();
    }

    /**
     * Create an instance of {@link AvailableBlockList }
     * 
     */
    public AvailableBlockList createAvailableBlockList() {
        return new AvailableBlockList();
    }

    /**
     * Create an instance of {@link CancelAppointmentRequest }
     * 
     */
    public CancelAppointmentRequest createCancelAppointmentRequest() {
        return new CancelAppointmentRequest();
    }

    /**
     * Create an instance of {@link GetRelationshipsRequest }
     * 
     */
    public GetRelationshipsRequest createGetRelationshipsRequest() {
        return new GetRelationshipsRequest();
    }

    /**
     * Create an instance of {@link RelationshipElement }
     * 
     */
    public RelationshipElement createRelationshipElement() {
        return new RelationshipElement();
    }
    
    /**
     * Create an instance of {@link PreferencesElement }
     * 
     */
    public PreferencesElement createPreferencesElement() {
    	return new PreferencesElement();
    }
    
    /**
     * Create an instance of {@link PreferencesSet }
     * 
     */
    public PreferencesSet createPreferencesSet() {
    	return new PreferencesSet();
    }

    /**
     * Create an instance of {@link ScheduleOwnerElement }
     * 
     */
    public ScheduleOwnerElement createScheduleOwnerElement() {
        return new ScheduleOwnerElement();
    }

    /**
     * Create an instance of {@link VisibleScheduleResponse }
     * 
     */
    public VisibleScheduleResponse createVisibleScheduleResponse() {
        return new VisibleScheduleResponse();
    }

    /**
     * Create an instance of {@link GetScheduleOwnerByIdRequest }
     * 
     */
    public GetScheduleOwnerByIdRequest createGetScheduleOwnerByIdRequest() {
        return new GetScheduleOwnerByIdRequest();
    }

    /**
     * Create an instance of {@link GetScheduleOwnerByIdResponse }
     * 
     */
    public GetScheduleOwnerByIdResponse createGetScheduleOwnerByIdResponse() {
        return new GetScheduleOwnerByIdResponse();
    }

    /**
     * Create an instance of {@link CreateAppointmentRequest }
     * 
     */
    public CreateAppointmentRequest createCreateAppointmentRequest() {
        return new CreateAppointmentRequest();
    }

    /**
     * Create an instance of {@link VisibleScheduleRequest }
     * 
     */
    public VisibleScheduleRequest createVisibleScheduleRequest() {
        return new VisibleScheduleRequest();
    }

    /**
     * Create an instance of {@link CreateAppointmentResponse }
     * 
     */
    public CreateAppointmentResponse createCreateAppointmentResponse() {
        return new CreateAppointmentResponse();
    }

    /**
     * Create an instance of {@link CancelAppointmentResponse }
     * 
     */
    public CancelAppointmentResponse createCancelAppointmentResponse() {
        return new CancelAppointmentResponse();
    }

    /**
     * Create an instance of {@link AvailableBlockElement }
     * 
     */
    public AvailableBlockElement createAvailableBlockElement() {
        return new AvailableBlockElement();
    }

    /**
     * Create an instance of {@link GetRelationshipsResponse }
     * 
     */
    public GetRelationshipsResponse createGetRelationshipsResponse() {
        return new GetRelationshipsResponse();
    }
    
    /**
     * Create an instance of {@link GetTargetAvailableBlockRequest }
     * 
     */
    public GetTargetAvailableBlockRequest createGetTargetAvailableBlockRequest() {
        return new GetTargetAvailableBlockRequest();
    }
    /**
     * Create an instance of {@link GetTargetAvailableBlockResponse }
     * 
     */
    public GetTargetAvailableBlockResponse createGetTargetAvailableBlockResponse() {
        return new GetTargetAvailableBlockResponse();
    }
    
    /**
     * Create an instance of {@link VisitorConflictsRequest }
     * 
     */
    public VisitorConflictsRequest createVisitorConflictsRequest() {
        return new VisitorConflictsRequest();
    }
    /**
     * Create an instance of {@link VisitorConflictsResponse }
     * 
     */
    public VisitorConflictsResponse createVisitorConflictsResponse() {
        return new VisitorConflictsResponse();
    }
    /**
     * Create an instance of {@link IsEligibleRequest }
     * 
     */
    public IsEligibleRequest createIsEligibleRequest() {
        return new IsEligibleRequest();
    }
    /**
     * Create an instance of {@link IsEligibleResponse }
     * 
     */
    public IsEligibleResponse createIsEligibleResponse() {
        return new IsEligibleResponse();
    }

}
